version: "3.9"

networks:
  traefik-net:
    external: true

services:
  frontend:
    image: "${FRONTEND_IMAGE}"
    container_name: frontend
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`adminzone.sendchap.com`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.routers.frontend.tls.certresolver=myresolver"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
    networks:
      - traefik-net
    deploy:
      restart_policy:
        condition: any
